#! /bin/sh

set -e

case "$1" in
    install|upgrade)
	rm -fv /etc/init.d/S99crond
	rm -fv /etc/crontabs/root
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
