#!/bin/sh

case "$1" in
	start)
		printf "Starting cron ... "
		if [ ! -L /var/spool/cron/crontabs ]; then
			mkdir -p /var/spool/cron
			ln -s /etc/crontabs /var/spool/cron/crontabs
		fi
		start-stop-daemon -S -q -m -b -p /var/run/dcron.pid --exec /usr/sbin/crond -- -f
		echo "done."
		;;
	stop)
		printf "Stopping cron ..."
		start-stop-daemon -K -q -p /var/run/dcron.pid
		echo "done."
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
		;;
esac
